---
title: "reading_from_web"
author: "Elaine Yanxi Chen"
date: 2022-10-13
output: 
  github_document
    

    
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## NSDUH data

```{r}
library(tidyverse)
library(rvest)
library(httr)
```

```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"
drug_use_html = read_html(url)
```

```{r}
drug_use_html %>% 
  html_table()
```

This gives all tables from the website. We only want the first table in that list.

```{r}
drug_use_html %>% 
  html_table() %>% 
  first() %>% 
  slice(-1)
```

slice is similar to filter but removes rows with specific row number 

## Star Wars data

```{r}
url = "https://www.imdb.com/list/ls070150896/"

swm_html = read_html(url)
```

How do I get the stuff I want

```{r}
sw_titles =
  swm_html %>%
  html_elements(".lister-item-header a") %>%
  html_text()

sw_runtime =
  swm_html %>%
  html_elements(".runtime") %>%
  html_text()

sw_money = 
  swm_html %>%
  html_elements(".text-small:nth-child(7) span:nth-child(5)") %>%
  html_text()

sw_df =
  tibble(
    title = sw_titles,
    runtime = sw_runtime,
    money = sw_money
  )
```

Napolean Dynamite review

```{r}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html = read_html(url)

review_titles = 
  dynamite_html %>%
  html_elements(".a-text-bold span") %>%
  html_text()

review_stars = 
  dynamite_html %>%
  html_elements("#cm_cr-review_list .review-rating") %>%
  html_text()

review_text = 
  dynamite_html %>%
  html_elements(".review-text-content span") %>%
  html_text()

reviews = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)

```

